# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160719_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Identificador')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
        migrations.AddField(
            model_name='module',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Visivel'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
