# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20160728_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
